title: Chroma 2022

description: |-
  Harvard-MIT Stable and Chromatic 
  Homotopy Theory Seminar Summer 2022
email: rushil_mallarapu@college.harvard.edu

icon: /assets/img/favicon.ico

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

